import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'WikiRocket!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className='bg-slate-800'>
        {/* navbar needs to be inside of the body */}
        <Navbar />
        {children}
      </body>
    </html>
  )
}
